version: '3'

services:
  node-app:
    container_name: test-center-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8001"
    environment:
      - PORT=5000
      - DB_ATLAS=mongodb://mongo_db:27017/test-center-db
      - SECRET_KEY_ALGO=HS256

